-include /env.mak

LIBNAME =
REQUIRES =

CFLAGS += -Werror -Wall -Wextra -fPIC -DPIC

SRCS = $(wildcard *.c)
OBJS = $(SRCS:%.c=%.o)

.PHONY: all clean

all: main.c
	$(CC) $(CFLAGS) $< $(LDFLAGS) $(LIBS)

clean:
	rm -f *.o *.so *.so.* *.a a.out

# vim:ft=make ts=4 sts=4 sw=4
